### ISSUE TITLE
Add generic handler metrics with the message type as a label

### ISSUE THREAD

**Issue by danielwitz** [wework/grabbit#143]
**Is your feature request related to a problem? Please describe.**
The handler metrics that grabbit exposes are per handler which makes creating generic dashboards difficult.

**Describe the solution you'd like**
I'd like generic metrics with the message type as a label, for the result counters the result would be a label as well

**Comment by rhinof** [comment]
@danielwitz will the metric still be on the handler only we add the message type or are you proposing we change the metric to report on messages instead of handlers?

**Comment by danielwitz** [comment]
@rhinof I think that the metric should have a handler name label and message type so people can choose the granularity of the dashboards. I think that after everyone uses this metric we can delete the other handlers metrics cause this one will cover all the cases
