### ISSUE TITLE
Logger is lost at initialization

### ISSUE THREAD

**Issue by vladshub** [wework/grabbit#200]
**Describe the bug**
Once the logger is passed to the builder it gets lost once the process starts running.
**To Reproduce**
1. initiate a logger with special fields
2. pass it to the builder
3. all logs from grabbit will lose the special fields (or any other configuration)

**Expected behavior**
Continue using the initial logger with special configuration and fields.
**Logs**
```
INFO[0000]/cmd/root.go:71 github.com/**/***/cmd.initLogger() starting                                     
{"file":"/cmd/root.go:116","func":"github.com/**/**/cmd.createBus","level":"info","msg":"bus starting","time":"2019-10-10T13:11:17+03:00"}
INFO[0000] initiating workers                            _service=**-web number_of_workers=1
INFO[0000] starting worker                               _service=**-web
{"file":"/cmd/root.go:132","func":"github.com/**/**/cmd.createBus","level":"info","msg":"bus started successfully","time":"2019-10-10T13:11:17+03:00"}
```
**Desktop (please complete the following information):**
 - Grabbit: [v1.1.5]

**Comment by rhinof** [comment]
After #201  when setting the custom logger grabbit does not add the service name to the log entries
