### ISSUE TITLE
Optimistic locking violation when saving saga instances should retry handler until success

### ISSUE THREAD

**Issue by rhinof** [wework/grabbit#52]
When a saga instance gets invoked and persisted to the saga store an optimistic locking error may occur due to concurrent invocations.
Currently when this happens the general retry strategy retries the message until success or until the set max retry count is exceeded and the message gets rejected.

In highly concurrent saga's this may cause unneeded operational efforts due to failed messages.
In case of concurrency violations we should retry the message until success.

**Comment by vladshub** [comment]
What happens if it actually should fail? We should add configuration around it and metrics for monitoring

**Comment by rhinof** [comment]
It should retry until success and the error should be "ignored" only if the error is due to a concurrency error other types of errors follow the regular retry flow

**Comment by avigailberger** [comment]
Also, this behaviour of retry upon concurrency error until success - needs to be extended to handlers (not just saga).

**Comment by rhinof** [comment]
What worries me is that if we provide such a mechanism it is a "loophole" that may lead to a service becoming unresponsive due to miss use or a bug in the way a developer may utilize this feature

**Comment by avigailberger** [comment]
we can have a different counter for this situations, something like 100 retries.. that should be sufficient and too much :)

**Comment by rhinof** [comment]
@avigailberger I was thinking about something along the lines you mentioned

**Comment by rhinof** [comment]
Decided to not proceed this route and instead allow configuration of the max retry policy and using a jittering backoff to reduce chances of conflicts #84
